import {Component} from '@angular/core';
import {Graph, GraphModel} from './graph/graph';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.html',
  styleUrls: ['./app.css'],
  imports: [
    Graph
  ]
})
export class App {
  graphData: GraphModel = {
    nodes: [
      { id: 'A', x: 0, y: 0 },
      { id: 'A+', x: 0, y: 1 },
      { id: 'AB+', x: 5, y: 1 },
      { id: 'B+', x: 7, y: 1 },
      { id: 'B', x: 7, y: 0 },
      { id: 'C+', x: 8, y: 1 },
      { id: 'C', x: 8, y: 0 },
      { id: 'NB+', x: 5, y: 2 },
      { id: 'DE+', x: 4, y: 2 },
      { id: 'D', x: 3, y: 2 },
      { id: 'E', x: 4, y: 3 },
      { id: 'AP+', x: 0, y: 5 },
      { id: 'HI+', x: 1, y: 5 },
      { id: 'J+', x: 2, y: 5 },
      { id: 'K+', x: 3, y: 5 },
      { id: 'LM+', x: 4, y: 5 },
      { id: 'N+', x: 5, y: 5 },
      { id: 'O+', x: 6, y: 5 },
      { id: 'ORV+', x: 7, y: 5 },
      { id: 'RV+', x: 7, y: 6 },
      { id: 'ST+', x: 7, y: 7 },
      { id: 'T', x: 7, y: 8 },
      { id: 'S', x: 8, y: 7 },
      { id: 'R', x: 6, y: 6 },
      { id: 'V', x: 8, y: 6 },
      { id: 'H', x: 1, y: 4 },
      { id: 'I', x: 1, y: 6 },
      { id: 'J', x: 2, y: 4 },
      { id: 'K', x: 3, y: 4 },
      { id: 'L', x: 4, y: 4 },
      { id: 'M', x: 4, y: 6 },
      { id: 'N', x: 5, y: 6 },
      { id: 'O', x: 6, y: 4 },
      { id: 'PQ+', x: 0, y: 7 },
      { id: 'Q', x: 0, y: 8 },
      { id: 'P', x: -1, y: 7 },
      { id: 'FGU+', x: -1, y: 5 },
      { id: 'F', x: -1, y: 4 },
      { id: 'G', x: -2, y: 5 },
      { id: 'U', x: -1, y: 6 },

    ],
    edges: [
      { from: 'A', to: 'A+' },
      { from: 'A', to: 'A+' },
      { from: 'A+', to: 'AP+' },
      { from: 'PQ+', to: 'AP+' },
      { from: 'HI+', to: 'AP+' },
      { from: 'HI+', to: 'J+' },
      { from: 'K+', to: 'J+' },
      { from: 'K+', to: 'LM+' },
      { from: 'N+', to: 'LM+' },
      { from: 'N+', to: 'O+' },
      { from: 'ORV+', to: 'O+' },
      { from: 'ORV+', to: 'C+' },
      { from: 'ORV+', to: 'RV+' },
      { from: 'ST+', to: 'RV+' },
      { from: 'C+', to: 'B+' },
      { from: 'AB+', to: 'B+' },
      { from: 'AB+', to: 'A+' },
      { from: 'AB+', to: 'NB+' },
      { from: 'N+', to: 'NB+' },
      { from: 'DE+', to: 'NB+' },
      { from: 'B', to: 'B+' },
      { from: 'C', to: 'C+' },
      { from: 'D', to: 'DE+' },
      { from: 'E', to: 'DE+' },
      { from: 'E', to: 'DE+' },
      { from: 'F', to: 'FGU+' },
      { from: 'G', to: 'FGU+' },
      { from: 'U', to: 'FGU+' },
      { from: 'H', to: 'HI+' },
      { from: 'I', to: 'HI+' },
      { from: 'J', to: 'J+' },
      { from: 'K', to: 'K+' },
      { from: 'L', to: 'LM+' },
      { from: 'M', to: 'LM+' },
      { from: 'N', to: 'N+' },
      { from: 'O', to: 'O+' },
      { from: 'R', to: 'RV+' },
      { from: 'V', to: 'RV+' },
      { from: 'S', to: 'ST+' },
      { from: 'T', to: 'ST+' },
      { from: 'Q', to: 'PQ+' },
      { from: 'P', to: 'PQ+' },
      { from: 'FGU+', to: 'AP+' },
    ]
  };
}
